# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('above_mp_threshold', models.BooleanField()),
                ('training', models.BooleanField()),
                ('internal', models.BooleanField()),
                ('has_budget_approval', models.BooleanField()),
                ('urgent', models.BooleanField()),
                ('urgency_description', models.TextField(max_length=10000)),
                ('description', models.TextField(max_length=10000)),
                ('submitted_at', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.Client')),
            ],
        ),
    ]
