# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('below_mp_threshold', models.NullBooleanField()),
                ('is_training', models.NullBooleanField()),
                ('is_internal', models.NullBooleanField()),
                ('client_has_approval', models.NullBooleanField()),
                ('client_contact', models.CharField(max_length=200)),
                ('urgency', models.TextField()),
                ('description', models.TextField()),
                ('submitted_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
