# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='client_contact',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
