# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='above_mp_threshold',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='has_budget_approval',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='internal',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='submitted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='training',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='urgency_description',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='urgent',
            field=models.NullBooleanField(),
        ),
    ]
