# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_auto_20170508_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
