version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - IS_RUNNING_IN_DOCKER=yup
